site_name: Municipal Software Group
nav:
    - Introduction: index.md
    - Getting Started: getting-started.md
    - Tables: tables.md
    - Data Conversion: data-conversion.md
    - Payments: payments.md
    - Printing: printing.md
theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
extra_css: [styles.css]